### ISSUE TITLE
Add a .gitignore file

### ISSUE THREAD

**Issue by davidromani** [Kizumi19/TimeZone-Practice#1]
Cal afegir un arxiu .gitignore para que ignore tot el contingut de la carpeta `vendor` i els seus subdirectoris.

**Comment by juliakb19** [comment]
Solucionat, també he afegit l'arxiu".save". Per cert, el que parlàvem de treballar per Feature Branch, ho havíem fet als 2 projectes, però no el dèiem així. Me n'he adonat mentre l'anava creant i utilitzant.
