### ISSUE TITLE
Improve output date format

### ISSUE THREAD

**Issue by davidromani** [Kizumi19/TimeZone-Practice#2]
Caldria mostrar la data amb el format que nosaltres entemen millor (dia/mes/any). Fixa't com apareix ara a la captura de pantalla, veruàs que et mostra primer el mes i després el dia...

![Captura de pantalla 2023-06-27 a les 13 08 01](https://github.com/Kizumi19/TimeZone-Practice/assets/698779/fde13eb4-7976-4096-91a8-66fda0c5c4cf)

**Comment by juliakb19** [comment]
Fet! Ara sí :)

Afegint una nova variable amb dues funcions que prenen la informació i la formaten com vulguem, podem resoldre aquest problema (hi ha una mica més d'informació al nou commit).

```
if($response->getStatusCode() == 200){
    $data = json_decode($response->getContent());
    $date = date('d-m-Y', strtotime($data->date)); // Afegint aquesta part 
    echo "Date ". $date.PHP_EOL; // I llavors l'invoquem aquí
    echo "Time ". $data->time.PHP_EOL;
    }
```
